name: charts_flutter
version: 0.8.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common: 0.8.0
  charts_common:
    git:
      url: git://github.com/janstol/charts
      path: charts_common
      ref: customized
#  charts_common:
#    path: ../charts_common/
  collection: ^1.14.11
  flutter:
    sdk: flutter
  intl: ^0.16.0
  logging: any
  meta: ^1.1.8


dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
